### ISSUE TITLE
change dappfile to new context definition

### ISSUE THREAD

**Issue by nmushegian** [dapphub/dapple#11]
Old version:

```
name: 'dappsys'
version: '0.0.1a'
source_dir: 'contracts'
dependencies:
    core: 'latest'
ignore:
    - kern/perm_db.sol
    - control/proxy_actor_test.sol
constants:
    ds_static_math_singleton: '0x0'
environments:
    dev.constants.ds_static_math_singleton: '0x1'
    prod.constants.ds_static_math_singleton: '0x2'
```

new version

```
name: 'my_dapple_package'
version: '0.0.1a'
source_dir: 'contracts'
ignore:
    - admin.sol
dependencies:
    core:
context:
    ethereum:
        "ens_app": 0x0
        "dappsys.ds_static_math": 0x2
    dev:
        "ens_app": 0x4
```
